be-core-setup : core 기본 구조 작성
chueok/sns-style-group-album pull request #18
Opened 2024-08-08 12:47 UTC by ch-jwoo

- @repo/core package 기본 domain 작성
- @repo/core package build 셋팅
    (barrelsby, nodemon 사용)
- @repo/core/common 에 util type, class 정의
    (ref : https://github.com/pvarentsov/typescript-clean-architecture/tree/master)
- server 에 @repo/core import

2024-08-10 07:24 UTC, Remian103 requested changes

2024-08-10 07:24 UTC, Remian103 commented on packages/be-core/src/domain/content/entity/content.abstract.ts
> +  }
referred 오타 확인 부탁드립니다~

오타랑 별개로 해당 경우처럼 server 쪽하고 변수명이 불일치하는 경우가 있을 것 같은데요.
이런 영역을 체크할 수 있는 장치가 추가되면 좋을 것 같습니다.
예를 들면 공통 타입 인터페이스 선언 후 implements 같은 걸 활용하는 방식같은게 있을 것 같아요.

해당 pr 에서는 오타만 수정하고, 제 의견 부분은 별도로 논의나 작업 진행하면 좋을 것 같습니다!

2024-08-10 07:24 UTC, Remian103 commented on packages/be-core/src/common/exception/exception.ts
> +    Error.captureStackTrace(this, this.constructor);
this.constructor 대신 Exception.new 를 작성하는건 어떨까요?

항상 new 로만 호출되는거면 error stack 에서 new 메소드 호출 스택이 생략될 수 있을 것 같아서요!

아니면 new 메소드 부분에서 Error.captureStackTrace 를 호출하는 것도 좋을 것 같은데 확인 부탁드립니다.


```ts

const error = new Exception();

Error.captureStackTrace(error, Exception.new);

return error;

```

2024-08-10 07:37 UTC, Remian103 commented on packages/be-core/src/common/entity/entity-with-cudtime.ts
> +  @IsDate()
https://stackoverflow.com/questions/61211664/how-to-allow-null-but-forbid-undefined
class-validator 사용 시 nullable 도 같이 고려되어야 할 것 같은데요. 확인 부탁드립니다.

2024-08-10 15:45 UTC, ch-jwoo commented on packages/be-core/src/domain/content/entity/content.abstract.ts
> +  }
중복 오타 송구합니다..

Domain Entity 와 DB Entity 는 단일책임원칙을 위해 분리한 것입니다.
1. Domain Entity : 도메인 로직 수행을 위함
2. DB Entity : DB 간의 관계 정의, DB 입출력을 위함

각각의 class를 변경하게 되는 상황은 아래와 같이 다를 수 있습니다.
1. Domain Entity : Domain 정책 혹은 로직 변경에 따름
2. DB Entity : DB 구성 변경 및 성능 최적화

현 상황에서는 중복이 많을 수 있으나,
이후 Domain 변경사항, DB 변경 사항을 분리하여 개발하기 위해 현재와 같은 구현 방식이 좋을 것 같습니다.

현재 상황에서 중복되는 property들을 공통 타입 인터페이스로 정의 시 서로 연관성이 생겨 추후 변경 사항 적용이 어려워 질 여지가 있습니다.

======================

여기 까지가 공식 답변이고,
사실 현재까지는 Domain 로직이라고 할만한게 각 Page에 데이터를 보여주는 역할이 주를 이루고 있습니다.

따라서 Domain Entity의 변경은 대부분 UI/UX의 변경을 위해 이루어질 확률이 높습니다.
이러한 경우 DB/Domain Entity 간에 강결합도 크게 문제될 소지는 없을 것 같습니다.

다만, 현 프로젝트에서 클린아키택처, 헥사고널 아키텍처의 철학들을 개발에 적용하고 싶다는 개발자의 개인 욕심이 있기 때문에 해당 부분은 현상 유지하는 쪽으로 제안드립니다

2024-08-10 16:07 UTC, ch-jwoo commented on packages/be-core/src/common/entity/entity-with-cudtime.ts
> +  @IsDate()
IsOptional() 추가했습니다.

2024-08-10 16:47 UTC, ch-jwoo commented on packages/be-core/src/common/exception/exception.ts
> +    Error.captureStackTrace(this, this.constructor);
피드백 주셔서 감사합니다.

이번에 말씀해주신 덕분에 저도 `Error.captureStackTrace` 에 대해 더 찾아봤는데,
Error.captureStackTrace의 두번째 인자(constructorOpt)는 StackTrace에서 **생략 할 오브젝트**를 정하는 것으로 보입니다.
해당 오브젝트 이전의 에러 트레이스를 생략하기 위한 것으로 생각되네요.

아래는 구현을 바꾸었을 때 Error Stack을 보여줍니다.

- `Error.captureStackTrace(this);`
  ![image](https://github.com/user-attachments/assets/9cc7abea-3ab3-4663-86c4-445fb7b599d8)

- `Error.captureStackTrace(this, this.constructor);`
   ![image](https://github.com/user-attachments/assets/1a1679f9-c8c6-44b2-9c5b-701bd310c531)

- `Error.captureStackTrace(this, Exception.new);`
   ![image](https://github.com/user-attachments/assets/dfdc6989-4cfb-458d-a161-b07fa501a104)

따라서 에러 스택에 Exception을 포함시키기 위해서는 ConstructorOpt 인자에 `Exception.new` 보다는 `this.constructor` 가 에러 분석 시 유리할 것 같습니다.

혹시 제가 잘못 이해한 부분이 있다면 다시 말씀해주세요~

2024-08-12 03:48 UTC, Remian103 commented on packages/be-core/src/common/exception/exception.ts
> +    Error.captureStackTrace(this, this.constructor);
에러분석 시에 Exception 은 단순 에러 객체를 의미하는거라 에러 분석 시에 굳이 포함되어야 하는 정보인가 하는 생각에 의견 드렸었습니다~
만약 에러 스택에 Exception 을 포함시키는게 유리하다고 생각되시면 그렇게 해도 무방할 것 같습니다!

2024-08-12 03:51 UTC, Remian103 commented on packages/be-core/src/domain/content/entity/content.abstract.ts
> +  }
이해했습니다~ 현상 유지하시죠!

2024-08-12 03:51 UTC, Remian103 approved these changes

2024-08-12 08:39 UTC, ch-jwoo commented on packages/be-core/src/common/exception/exception.ts
> +    Error.captureStackTrace(this, this.constructor);
아! 말씀해주신 바를 제가 발못 이해하고 있었네요.

단순히 Error throw하는 부분이니 생략 하도록 제안 주신거군요.

제 생각에도 굳이 Exeption class 를 생성하는 부분까지는 추적할 필요 없는 것 같아서 해당 부분 수정 후 머지하겠습니다.

2024-08-12 17:25 UTC, merged